backend:
  name: github
  repo:  sunkickr/gatsby-starter-hello-world 

media_folder: static/assets
public_folder: /assets

collections:
  - name: blog
    label: Blog
    folder: blog
    slug: "{{slug}}"
    create: true
    fields:
      - { name: title, label: Title }
      - { name: description, label: Description, widget: string}
      - { name: heroImagePath, label: heroImagePath}
      - { name: authors, label: Authors}
      - { name: avatar, label: Avatar}
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - { name: body, label: Body, widget: markdown }